### ISSUE TITLE
MVPリリースレビュー

### ISSUE THREAD

**Issue by kenchasonakai** [kobayashi-yuuki-44/MT_Life#106]
MVPリリースおめでとうございます
このissueのコメントに本リリース予定日のご回答をお願いいたします
以下にレビュー内容を記載します

## 過去問機能
次へボタンが出るときと出ない時があり、過去問の選択肢を選択した後の導線が途切れてしまうので(メモを作成しても別の画面に行くとかが無い)次のアクションに繋がる導線を作ってあげると良いかと思います
例: とりあえずどんどん問題を解いて欲しいから解説を出さずに次へボタンでひたすら問題を解いてもらう、一問一問しっかりと深ぼって欲しいから一問ごとに解説を表示してメモを作成してもらう、何問かまとめて解いてもらって解き終わったらノートや単語帳をしっかりと作ってもらう等
[![Image from Gyazo](https://t.gyazo.com/teams/startup-technology/efa404b39a1f71ddbc6d5d3456ad8ddc.png)](https://startup-technology.gyazo.com/efa404b39a1f71ddbc6d5d3456ad8ddc)

## ノート機能
ノートが保存される条件がわかりにくいので説明を追加するか、Notionなどと同じようにリアルタイムで保存されるような形にすると良いかと思います
[![Image from Gyazo](https://t.gyazo.com/teams/startup-technology/b032acc216cb5b20fd1a72f6abea0a08.gif)](https://startup-technology.gyazo.com/b032acc216cb5b20fd1a72f6abea0a08)

## 単語帳機能
他の人のワードが消せてしまっているような気がするので確認してください

## 機能面
技術的にアピールできるポイントが少なく感じるので本リリースまでの実装を進めていってください

## UI・UX面
いろんな人に実際に使ってもらってフィードバックを元に使いやすい形に改善していきましょう

**Comment by kobayashi-yuuki-44** [comment]
ありがとうございます。
頂いたレビュー内容の機能実装を急いで進め、再度レビュー提出させていただきます。
本リリースは5月20日を予定しています。
よろしくお願いいたします。
