### ISSUE TITLE
メモ機能に関する質問

### ISSUE THREAD

**Issue by kobayashi-yuuki-44** [kobayashi-yuuki-44/MT_Life#83]
## 実装したい機能
問題回答画面にメモ機能を追加したい
①ユーザーがメモを登録している場合、問題文・「Answer!」ボタンの下に「メモを表示」ボタンを表示(このボタンを押すと「メモを表示」「メモを非表示」に切り替わる)
②「メモを表示」ボタンを押すと登録済みのメモ内容が表示される。(この時のボタンは「メモを非表示」)

## 現状解決できない問題
・controllers直下にあるStimulusコントローラーのファイルに記述後、views/questions/show.html.erbで呼び出しても反映されない。
・app/javascript直下にjsファイルを作成しても反映されず。
・views/layouts/application.html.erb内に直接js内容を記述した場合は反映され、機能実装ができる。

controllers直下にあるStimulusコントローラーのファイル作成後、検証ツールでSources・Networkタブを確認すると読み込みはされているようでした。Consoleタブには特にエラーなど出ていません。

Stimulusコントローラーまたは、javascriptファイルを使用して機能を実装したいと考えています。
原因を見つけられず、ご教授いただけますと幸いです。

**Comment by Tsuchiya2** [comment]
↑のテキストだけだと情報が少なく不透明なところが多いため、スクリーンショットなどを活用して状況が分かるように共有いただけますか。

それとは別ですが、`console.log('xxxx');`をJavaScriptのコードに加えて、ブラウザのコンソールにそれが表示されるか確認してみましょう。表示されていなければ、そのコード自体が実行されていないか、ファイル自体が読み込まれていないか等々、状況を把握・可能性を1つずつ潰していく形で状況把握から進めてみてください！

**Comment by Tsuchiya2** [comment]
どんなファイルがあって、どこにどんなコードを書いているか分からないので一概には言えませんが...

`console.log('xxxx');`を記載されたとのことですが、画像のコンソールに「xxx」が表示されていないように見えるのですが、どこを見て`console.log('xxxx');`が読み込まれていると判断されたのか教えていただけますか？画像から分かることとしては`console.log('xxxx');`は読み込まれていないか、実行されていないことが分かりました。

![image](https://github.com/kobayashi-yuuki-44/MT_Life/assets/61481161/20bdf2bd-4805-4200-b653-a7bc43e37408)


```javascript
# app/..../hoge.js
console.log('xxxx');
```

↑を読み込ませるファイル（app/javascript/application.jsなど、importmap, esbuild, webpackなど使っているものによってや設定、Railsのバージョンによって異なります）に、hoge.jsを読み込ませる記載があるかの確認などから取り組みましょう。

**Comment by kobayashi-yuuki-44** [comment]
ご対応ありがとうございます。
ファイルなどを整理し、新たに作成し直しました。
現在のファイルについて、pushしてからの変更箇所を下記に記載します。

[app/javascript/application.js]
```
// Configure your import map in config/importmap.rb. Read more: https://github.com/rails/importmap-rails
import "@hotwired/turbo-rails";
import "controllers";
import "./toggle_memo";
```

[app/javascript/toggle_memo.js]
```
console.log('Toggle memo script loaded');
document.addEventListener("DOMContentLoaded", function() {
  console.log("turbo:load event triggered");
  const toggleButton = document.getElementById("toggle-memo");
  const memoContent = document.getElementById("memo-content");
  console.log({ toggleButton, memoContent });

  if (toggleButton && memoContent) {
    console.log("Adding event listener");
    toggleButton.addEventListener("click", function() {
      console.log("Toggle button clicked");
      memoContent.style.display = memoContent.style.display === "none" ? "block" : "none";
      toggleButton.textContent = memoContent.style.display === "block" ? "メモを隠す" : "メモを見る";
    });
  }
});
```

[views/layouts/application.html.erb]：scriptを直接記述していたのでそれを削除した内容になります。
```
<!DOCTYPE html>
<html>
  <head>
    <title>MTLife</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://fonts.googleapis.com/css2?family=Caveat:wght@600&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=RocknRoll+One&display=swap" rel="stylesheet">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="flex flex-col min-h-screen">
    <%= render 'shared/header' %>
    <main class="flex-grow">
      <%= render 'shared/flash_message' %>
      <%= yield %>
    </main>
    <%= render 'shared/footer' %>
  </body>
</html>
```

[config/importmap.rb]
```
# Pin npm packages by running ./bin/importmap

pin "application"
pin "@hotwired/turbo-rails", to: "turbo.min.js", preload: true
pin "@hotwired/stimulus", to: "stimulus.min.js"
pin "@hotwired/stimulus-loading", to: "stimulus-loading.js"
pin_all_from "app/javascript/controllers", under: "controllers"
pin "toggle_memo", to: "toggle_memo.js"
```

上記のように作成・変更を行いました。
ユーザーのメモ登録がある場合、「メモを表示」ボタンは表示されるのですがクリックしても反応しません。下記画面の状態です。

<img width="1440" alt="e2394fe0683b09333a5187d4cc7cec9c" src="https://github.com/kobayashi-yuuki-44/MT_Life/assets/131279389/28620981-8d13-4939-bce4-bd4db477cfa4">


そこで、検証ツールで確認を行いました。

<img width="1440" alt="538af60935675c7c70bc75b26e916865" src="https://github.com/kobayashi-yuuki-44/MT_Life/assets/131279389/408ee693-048d-4e88-826e-07308ac4d1c7">

<img width="1437" alt="8c28ffaa9ea9e3c90c2943594690b99c" src="https://github.com/kobayashi-yuuki-44/MT_Life/assets/131279389/399ddfa0-17ea-4832-a885-3b69d12f46ad">

<img width="1438" alt="e1fa83439a81bbd0b21f313939403854" src="https://github.com/kobayashi-yuuki-44/MT_Life/assets/131279389/234c1eb4-b584-4ef5-b0dc-180d194cee0b">

<img width="1430" alt="fa444db5547ce5640f75a256d659ea2e" src="https://github.com/kobayashi-yuuki-44/MT_Life/assets/131279389/eef584e3-59d1-4957-a0b6-b8bf74f44a46">


app/javascript/toggle_memo.jsファイルの先頭に`console.log('Toggle memo script loaded');`を記述しましたが、Console上には何も表示されませんでした。スクリプトが読み込まれていないと判断しました。
jsファイルの作成場所とimportmap.rbに読み込みの記述は一致しているように思いますが、なぜ読み込まれないのでしょうか。

**Comment by Tsuchiya2** [comment]
株式会社万葉さんのnoteがもしかしたら参考になるかもしれません。内容確認して「ページ遷移時にフルリロードする」とか試してみてください。

https://note.com/everyleaf/n/n5c0f123b20a6#17ca34f9-cf23-49a0-b1a8-df804e3bd14a

**Comment by kobayashi-yuuki-44** [comment]
いただいた記事を確認し下記のように修正したところ、javascriptファイルが全て読み込まれるようになりました...！

[views/questions/show.html.erb]：headブロック内に`<meta name="turbo-visit-control" content="reload">`を追加
```
<% content_for :head do %>
  <meta name="turbo-visit-control" content="reload">
  <%= javascript_import_module_tag "toggle_memo" %>
<% end %>

<%= render 'questions/question_detail', question: @question, answer: @answer %>

<% if @question.memos.any? %>
  <button id="toggle-memo" class="btn btn-info">メモを見る</button>
  <div id="content" style="display:none;">
    <% @question.memos.each do |memo| %>
      <div class="memo">
        <%= memo.content %>
      </div>
    <% end %>
  </div>
<% end %>

<%= form_with(model: [@question, @question.memos.build], local: true) do |form| %>
  <div class="field">
    <%= form.label :content, "メモ" %>
    <%= form.text_area :content %>
  </div>
  <%= form.submit "メモを保存", class: "btn btn-primary" %>
<% end %>
```

ビューでjavascriptファイルを呼び出す記述ができていなかったことと、Turbo Driveの影響を受けないよう特定のページをフルリロードするよう修正することで問題を解決できました。
本当にありがとうございました。
